### ISSUE TITLE
LICENSE discussion

### ISSUE THREAD

**Issue by lionelyoung** [eMBee/vimeo-download#2]
Discussion on license

All my contributions for this will be unlicense: http://unlicense.org/

@eMBee please add any authors

**Comment by eMBee** [comment]
@alexeygrigorev @tayiorbeii @paschoaletto could you please look at this question?

@lionelyoung proposes to publish this under the unlicense. 
since all of you contributed to the code, your input on the license is appreciated.

personally i think if we can't get a consensus, then the primary choice of license should be with @alexeygrigorev since his code is the start.

myself i favor the GPL in some form or at least something compatible (which i believe the unlicense is) but given my minimal contribution i am fine with any other choice.

**Comment by alexeygrigorev** [comment]
my code is WTF PL, but feel free to change that :-)

**Comment by eMBee** [comment]
uh, sorry, could you elaborate please :-)

**Comment by alexeygrigorev** [comment]
if it's the questions to me, the elaborate answer is "I don't care, do WFT you want" (that's basically what the licence says)

**Comment by tayiorbeii** [comment]
Whatever is clever.

**Comment by paschoaletto** [comment]
Same from here. This code helped me on what I needed, I just want to leave it and help some others on the same situation.

**Comment by eMBee** [comment]
excellent, thank you everyone.

as there are no objections, unlicense it is then. @lionelyoung 

i feel the same as @paschoaletto btw, it's my motivation to collect all branches into this repo. i probably won't do much with it until i have that problem again. 

maintenance ought to fall on whoever uses the code the most or last :-)

everyone has been given write access so that anyone can take over at any time even with out forking.

**Comment by eMBee** [comment]
excellent, thank you everyone.

as there are no objections, unlicense it is then. (@lionelyoung)
and as it turns out, youtube-dl is also using the unlicense, so we are in good company with that choice.

i feel the same as @paschoaletto btw, it's my motivation to collect all branches into this repo. i probably won't do much with it until i have that problem again. 

maintenance ought to fall on whoever uses the code the most or last :-)

everyone has been given write access so that anyone can take over at any time even with out forking.
